# Generated by Django 2.1.7 on 2019-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationuser',
            name='role',
            field=models.CharField(choices=[('RG', 'Regular'), ('AD', 'Administrator')], default='AD', max_length=10, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
